In [22]:
import numpy as np

In [23]:
# loss值 一个最后的数
loss_index_mean = np.load('/data/AI-Tianlong/openmmlab/mmpretrain/configs_new/atl-paper-test400e-addndvi/1-loss_index_mean-数.npy')
nan_loss_index_mean = np.argwhere(np.isnan(loss_index_mean))
loss_index_mean

array(nan, dtype=float32)

In [26]:
# 查看 target_index loss 的nan
loss_index_mean_67 = np.load('/data/AI-Tianlong/openmmlab/mmpretrain/configs_new/atl-paper-test400e-addndvi/2-loss_index_mean-67.npy')
nan_loss_index_mean_67_67 = np.argwhere(np.isnan(loss_index_mean_67))
print(f'target_index 的loss 有 {nan_loss_index_mean_67_67.shape[0]} 个 nan')  # 某一张图的 某几个patch中的loss是nan
print(f'loss_index_mean_67.shape {loss_index_mean_67.shape}')
nan_loss_index_mean_67_67# 102760448 什么意思，整个一张卡上的batch 的loss都是 nan？？

target_index 的loss 有 102760448 个 nan
loss_index_mean_67.shape (512, 196, 1024)


array([[   0,    0,    0],
       [   0,    0,    1],
       [   0,    0,    2],
       ...,
       [ 511,  195, 1021],
       [ 511,  195, 1022],
       [ 511,  195, 1023]])

In [28]:
# 查看 target_index_token 的值 这里 没有nan啊？

target_rs_index = np.load('./3-target_index-token.npy')
nan_target_rs_index = np.argwhere(np.isnan(target_rs_index)) # 这个里面就有nan！！！
print(f'target_rs_index.shape {target_rs_index.shape}')
print(nan_target_rs_index.shape)
print(nan_target_rs_index)

target_rs_index.shape (512, 196, 1024)
(0, 3)
[]


In [29]:
# 查看unpatchy 中是否有nan 既有nan
unpatchify_target_index = np.load('./3-unpatchify-target_index-token.npy')
nan_unpatchify = np.argwhere(np.isnan(unpatchify_target_index))  #那一列都是nan
print(nan_unpatchify.shape)
print(nan_unpatchify)

(0, 4)
[]


In [34]:
# 查看unpatchy 中是否有nan 既有nan
unpatchify_target = np.load('./4-unpatchify_target.npy')
unpatchify_pred = np.load('./4-unpatchify_pred.npy')
nan_unpatchify_pred = np.argwhere(np.isnan(unpatchify_pred))  #那一列都是nan
nan_unpatchify_pred

array([[  0,   0,   0,   0],
       [  0,   0,   0,   1],
       [  0,   0,   0,   2],
       ...,
       [511,   9, 223, 221],
       [511,   9, 223, 222],
       [511,   9, 223, 223]])

In [21]:
from ATL_Tools.ATL_gdal import save_array_to_tif
save_array_to_tif(unpatchify_target_index[413].transpose(1,2,0), './图413-nan_index.tif', Band=4)
save_array_to_tif(unpatchify_target[413].transpose(1,2,0), './图413-unpatchify_target.tif', Band=10)
save_array_to_tif(unpatchify_pred[413].transpose(1,2,0), './图413-unpatchify_pred.tif', Band=10)


In [16]:
unpatchify_target_index[413].transpose(1,2,0).shape

(224, 224, 4)

In [17]:
np.argwhere(np.isnan(unpatchify_target_index[413].transpose(1,2,0)))

array([[  0, 223,   1],
       [  1, 223,   1],
       [  2, 223,   1],
       [  3, 223,   1],
       [  4, 223,   1],
       [  5, 223,   1],
       [  6, 223,   1],
       [  7, 223,   1],
       [  8, 223,   1],
       [  9, 223,   1],
       [ 10, 223,   1],
       [ 11, 223,   1],
       [ 12, 223,   1],
       [ 13, 223,   1],
       [ 14, 223,   1],
       [ 15, 223,   1],
       [ 16, 223,   1],
       [ 17, 223,   1],
       [ 18, 223,   1],
       [ 19, 223,   1],
       [ 20, 223,   1],
       [ 21, 223,   1],
       [ 22, 223,   1],
       [ 23, 223,   1],
       [ 24, 223,   1],
       [ 25, 223,   1],
       [ 26, 223,   1],
       [ 27, 223,   1],
       [ 28, 223,   1],
       [ 29, 223,   1],
       [ 30, 223,   1],
       [ 31, 223,   1],
       [ 32, 223,   1],
       [ 33, 223,   1],
       [ 34, 223,   1],
       [ 35, 223,   1],
       [ 36, 223,   1],
       [ 37, 223,   1],
       [ 38, 223,   1],
       [ 39, 223,   1],
       [ 40, 223,   1],
       [ 41, 223

In [38]:
# 查看pred_rs_index 是否有nan
target_rs_index = np.load('./3-target_index.npy')
nan_target_rs_index = np.argwhere(np.isnan(target_rs_index))
# print(f'有 {nan_target_rs_index.shape[0]} 个loss是nan, ' )
print(f'nan 的位置：\n {nan_target_rs_index}') # 有 
print(target_rs_index[nan_target_rs_index[i][0], nan_target_rs_index[i][1], nan_target_rs_index[i][2]] for i in nan_target_rs_index)

nan 的位置：
 [[ 413   13   61]
 [ 413   13  125]
 [ 413   13  189]
 [ 413   13  253]
 [ 413   13  317]
 [ 413   13  381]
 [ 413   13  445]
 [ 413   13  509]
 [ 413   13  573]
 [ 413   13  637]
 [ 413   13  701]
 [ 413   13  765]
 [ 413   13  829]
 [ 413   13  893]
 [ 413   13  957]
 [ 413   13 1021]
 [ 413   27   61]
 [ 413   27  125]
 [ 413   27  189]
 [ 413   27  253]
 [ 413   27  317]
 [ 413   27  381]
 [ 413   27  445]
 [ 413   27  509]
 [ 413   27  573]
 [ 413   27  637]
 [ 413   27  701]
 [ 413   27  765]
 [ 413   27  829]
 [ 413   27  893]
 [ 413   27  957]
 [ 413   27 1021]
 [ 413   41   61]
 [ 413   41  125]
 [ 413   41  189]
 [ 413   41  253]
 [ 413   41  317]
 [ 413   41  381]
 [ 413   41  445]
 [ 413   41  509]
 [ 413   41  573]
 [ 413   41  637]
 [ 413   41  701]
 [ 413   41  765]
 [ 413   41  829]
 [ 413   41  893]
 [ 413   41  957]
 [ 413   41 1021]
 [ 413   55   61]
 [ 413   55  125]
 [ 413   55  189]
 [ 413   55  253]
 [ 413   55  317]
 [ 413   55  381]
 [ 413   55  445]


In [40]:
target_rs_index[413, 13, 61]

nan

In [16]:
# 查找nan_loss中的nan的位置
nan_loss = np.load('nan_loss.npy')
nan_index = np.argwhere(np.isnan(nan_loss))
# np.isnan(nan_loss).shape
nan_index   # [413, 13 61]---> 第413个图像的 第13个patch中的第61个是nan？？？ 怎么还能是nan呢？ 

array([[ 413,   13,   61],
       [ 413,   13,  125],
       [ 413,   13,  189],
       [ 413,   13,  253],
       [ 413,   13,  317],
       [ 413,   13,  381],
       [ 413,   13,  445],
       [ 413,   13,  509],
       [ 413,   13,  573],
       [ 413,   13,  637],
       [ 413,   13,  701],
       [ 413,   13,  765],
       [ 413,   13,  829],
       [ 413,   13,  893],
       [ 413,   13,  957],
       [ 413,   13, 1021],
       [ 413,   27,   61],
       [ 413,   27,  125],
       [ 413,   27,  189],
       [ 413,   27,  253],
       [ 413,   27,  317],
       [ 413,   27,  381],
       [ 413,   27,  445],
       [ 413,   27,  509],
       [ 413,   27,  573],
       [ 413,   27,  637],
       [ 413,   27,  701],
       [ 413,   27,  765],
       [ 413,   27,  829],
       [ 413,   27,  893],
       [ 413,   27,  957],
       [ 413,   27, 1021],
       [ 413,   41,   61],
       [ 413,   41,  125],
       [ 413,   41,  189],
       [ 413,   41,  253],
       [ 413,   41,  317],
 